rabbitmq:
  host: 'rabbitmq'
  port: '5672'
  user: 'guest'
  pass: 'guest'
database:
  host: 'env(DB_HOST)'
  port: '3306'
  user: 'env(DB_USER)'
  pass: 'env(DB_PASS)'
  dbname: 'dieselnet_api'
  driver: 'pdo_mysql'
portal:
  infoUrl: 'http://dev.dieselnet.co.il/en/api/get'
  updateUrl: 'http://dev.dieselnet.co.il/en/api/update'
  registerUrl: 'http://dev.dieselnet.co.il/en/api/register'
  secret: 'env(PORTAL_SECRET)'
